import {DEFAULT_MODELS,getModel,hfResolve} from './registry.js';
const WLLAMA_VER='2.4.0',WLLAMA_BASE=`https://cdn.jsdelivr.net/npm/@wllama/wllama@${WLLAMA_VER}/esm`;
let _wllamaMod=null;
async function loadWllama(){if(_wllamaMod)return _wllamaMod;_wllamaMod=await import(`${WLLAMA_BASE}/index.js`);return _wllamaMod;}
function defaultPaths(){return{'single-thread/wllama.wasm':`${WLLAMA_BASE}/single-thread/wllama.wasm`,'multi-thread/wllama.wasm':`${WLLAMA_BASE}/multi-thread/wllama.wasm`};}
function decorateLoadError(e,bytes){const m=String(e&&e.message||e);const isTAL=/Invalid typed array length|RangeError.*ArrayBuffer|out of memory|allocation/i.test(m);const isoOk=typeof self!=='undefined'&&self.crossOriginIsolated;const sizeMB=Math.round((bytes||0)/1048576);if(isTAL){const tips=[];tips.push(`The browser refused to allocate ~${sizeMB} MB for this model.`);if(!isoOk)tips.push('Cross-origin isolation is OFF — SharedArrayBuffer / multi-thread WASM unavailable; single-thread mode has tighter memory limits. Register coi-sw.js (provided) to enable it on static hosts.');tips.push('Try a smaller model (under 1 GB on mobile, under 4 GB on most desktop browsers).');tips.push('On Chrome desktop, increase the V8 heap if possible, or close other tabs.');const err=new Error('Load failed: '+m+'\n\n'+tips.map(t=>'• '+t).join('\n'));err.cause=e;err.kind='memory';return err;}return e;}
export function isCrossOriginIsolated(){return typeof self!=='undefined'&&self.crossOriginIsolated===true;}
export class AmniLLMEngine{
constructor(opts={}){this.opts=opts;this.engine=null;this.modelInfo=null;this.loading=false;this.history=[];this.onProgress=opts.onProgress||(()=>{});this.onStatus=opts.onStatus||(()=>{});}
async load(modelSpec,loadCfg={}){if(this.loading)throw new Error('AmniLLM: already loading');this.loading=true;try{this.onStatus('init','Initializing wllama runtime');const mod=await loadWllama();const Wllama=mod.Wllama;if(!Wllama)throw new Error('wllama module missing Wllama export');const paths=this.opts.wasmPaths||defaultPaths();this.engine=new Wllama(paths,{logger:{debug:()=>{},log:()=>{},warn:console.warn,error:console.error}});const cfg={...loadCfg,n_ctx:loadCfg.n_ctx||4096,n_threads:loadCfg.n_threads||Math.max(1,Math.min(4,(navigator.hardwareConcurrency||2)-1)),progressCallback:p=>{const pct=p.total?Math.round(p.loaded/p.total*100):0;this.onProgress({loaded:p.loaded,total:p.total,pct});this.onStatus('downloading',`Downloading ${pct}%`);}};let url,info;if(typeof modelSpec==='string'){const m=getModel(modelSpec);if(m){url=m.hfUrl;info={...m};}else if(/^https?:/i.test(modelSpec)){url=modelSpec;info={id:'custom',name:modelSpec.split('/').pop(),hfUrl:modelSpec};}else throw new Error('Unknown model id and not a URL: '+modelSpec);}else if(modelSpec&&modelSpec.url){url=modelSpec.url;info={id:modelSpec.id||'custom',name:modelSpec.name||modelSpec.url.split('/').pop(),hfUrl:modelSpec.url};}else if(modelSpec&&modelSpec.file){this.onStatus('loading','Loading from local file');try{await this.engine.loadModel([modelSpec.file],cfg);}catch(e){throw decorateLoadError(e,modelSpec.file.size);}this.modelInfo={id:'local',name:modelSpec.file.name,hfUrl:null,sizeMB:Math.round(modelSpec.file.size/1048576)};this.onStatus('ready',`Ready (${this.modelInfo.name})`);return this.modelInfo;}else throw new Error('AmniLLM.load: invalid modelSpec');this.onStatus('downloading',`Downloading ${info.name}`);try{await this.engine.loadModelFromUrl(url,cfg);}catch(e){throw decorateLoadError(e,(info.sizeMB||0)*1048576);}this.modelInfo=info;this.onStatus('ready',`Ready (${info.name})`);return info;}finally{this.loading=false;}}
async unload(){if(!this.engine)return;try{await this.engine.exit();}catch(e){}this.engine=null;this.modelInfo=null;this.history=[];this.onStatus('idle','Unloaded');}
isReady(){return!!this.engine&&!!this.modelInfo;}
getModelInfo(){return this.modelInfo;}
async chat(messages,opts={}){if(!this.isReady())throw new Error('AmniLLM not ready');const o={temperature:opts.temperature??0.4,max_tokens:opts.max_tokens??512,top_p:opts.top_p??0.95,stop:opts.stop};return await this.engine.createChatCompletion(messages,{...o,stream:false});}
async*chatStream(messages,opts={}){if(!this.isReady())throw new Error('AmniLLM not ready');const o={temperature:opts.temperature??0.4,max_tokens:opts.max_tokens??512,top_p:opts.top_p??0.95,stop:opts.stop,stream:true};const stream=await this.engine.createChatCompletion(messages,o);for await(const ch of stream){const d=ch.currentText||ch.delta||ch.token||'';if(d)yield{delta:d,raw:ch};}}
get chatCompletions(){return{create:async(req)=>{if(req.stream)return this.chatStream(req.messages,req);const text=await this.chat(req.messages,req);return{choices:[{message:{role:'assistant',content:text},finish_reason:'stop'}]};}};}
get completions(){return this.chatCompletions;}
}
export async function createEngine(modelSpec,opts={}){const e=new AmniLLMEngine(opts);await e.load(modelSpec,opts.loadCfg||{});return e;}
export {DEFAULT_MODELS,getModel,hfResolve,decorateLoadError};
export const AMNI_LLM_VERSION='0.1.0';
export const COMPUTE_BACKEND={engine:'wllama',version:WLLAMA_VER,kernel:'llama.cpp',license:'MIT',source:'https://github.com/ngxson/wllama'};
